package com.ikkong.goods.service;

import com.ikkong.core.base.service.IService;
import com.ikkong.goods.model.Goodssplog;

/**
 * Generated by Blade.
 * 2018-07-25 09:28:36
 */
public interface GoodssplogService extends IService<Goodssplog>{

}
