package com.ikkong.casher.service.impl;

import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.casher.model.Casher;
import com.ikkong.casher.service.CasherService;

/**
 * Generated by Blade.
 * 2018-07-23 14:59:02
 */
public class CasherServiceImpl extends BaseService<Casher> implements CasherService{

}
