package com.ikkong.casher.service.impl;

import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.casher.model.Casherlog;
import com.ikkong.casher.service.CasherlogService;

/**
 * Generated by Blade.
 * 2018-07-23 16:28:52
 */
public class CasherlogServiceImpl extends BaseService<Casherlog> implements CasherlogService{

}
