package com.ikkong.casher.service.impl;

import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.casher.model.Casherdetail;
import com.ikkong.casher.service.CasherdetailService;

/**
 * Generated by Blade.
 * 2018-07-23 14:58:05
 */
public class CasherdetailServiceImpl extends BaseService<Casherdetail> implements CasherdetailService{

}
