package com.ikkong.files.model;

import org.beetl.sql.core.annotatoin.AutoID;
import org.beetl.sql.core.annotatoin.Table;
import com.ikkong.core.annotation.BindID;
import com.ikkong.core.model.BaseModel;

import java.util.Date;

/**
 * Generated by Blade.
 * 2018-07-27 16:36:20
 */
@Table(name = "nsl_files_vislog")
@BindID(name = "id")
@SuppressWarnings("serial")
public class Filesvislog extends BaseModel {
    	private Integer id;
    	private Integer f_id; //文件
    	private Integer u_id; //操作人
	private Integer p_id;
    	private String after; //操作后
    	private String afterid; //操作后(id)
    	private String befor; //操作前
    	private String beforid; //操作前(id)
    	private String visible; //增加可见人
    	private Date date; //操作时间

    	@AutoID
    	public Integer getId() {
    		return id;
    	}

    	public void setId(Integer id) {
    		this.id = id;
    	}

    	public Integer getP_id() {
    		return p_id;
    	}

    	public void setP_id(Integer p_id) {
    		this.p_id = p_id;
    	}

	public Integer getF_id() {
		return f_id;
	}

	public void setF_id(Integer f_id) {
		this.f_id = f_id;
	}

    	public Integer getU_id() {
    		return u_id;
    	}

    	public void setU_id(Integer u_id) {
    		this.u_id = u_id;
    	}

    	public String getAfter() {
    		return after;
    	}

    	public void setAfter(String after) {
    		this.after = after;
    	}

    	public String getAfterid() {
    		return afterid;
    	}

    	public void setAfterid(String afterid) {
    		this.afterid = afterid;
    	}

    	public String getBefor() {
    		return befor;
    	}

    	public void setBefor(String befor) {
    		this.befor = befor;
    	}

    	public String getBeforid() {
    		return beforid;
    	}

    	public void setBeforid(String beforid) {
    		this.beforid = beforid;
    	}

    	public String getVisible() {
    		return visible;
    	}

    	public void setVisible(String visible) {
    		this.visible = visible;
    	}

    	public Date getDate() {
    		return date;
    	}

    	public void setDate(Date date) {
    		this.date = date;
    	}

}
