package com.ikkong.files.model;

import org.beetl.sql.core.annotatoin.AutoID;
import org.beetl.sql.core.annotatoin.Table;
import com.ikkong.core.annotation.BindID;
import com.ikkong.core.model.BaseModel;

import java.util.Date;

/**
 * Generated by Blade.
 * 2018-07-16 10:24:02
 */
@Table(name = "nsl_files_log")
@BindID(name = "id")
@SuppressWarnings("serial")
public class Fileslog extends BaseModel {
    	private Integer id;
    	private Integer f_id; //文件名
    	private Integer ispass; //是否通过
    	private Integer u_id; //审批人
    	private Integer version;
    	private String opinion; //审核意见
	private String review; //回复意见
    	private Date date; //审批时间
	private Date fudate; //审批时间

    	@AutoID
		public String getReview() {
			return review;
		}

	public void setReview(String review) {
		this.review = review;
	}

    	public Integer getId() {
    		return id;
    	}

    	public void setId(Integer id) {
    		this.id = id;
    	}

    	public Integer getF_id() {
    		return f_id;
    	}

    	public void setF_id(Integer f_id) {
    		this.f_id = f_id;
    	}

    	public Integer getIspass() {
    		return ispass;
    	}

    	public void setIspass(Integer ispass) {
    		this.ispass = ispass;
    	}

    	public Integer getU_id() {
    		return u_id;
    	}

    	public void setU_id(Integer u_id) {
    		this.u_id = u_id;
    	}

    	public Integer getVersion() {
    		return version;
    	}

    	public void setVersion(Integer version) {
    		this.version = version;
    	}

    	public String getOpinion() {
    		return opinion;
    	}

    	public void setOpinion(String opinion) {
    		this.opinion = opinion;
    	}

    	public Date getDate() {
    		return date;
    	}

    	public void setDate(Date date) {
    		this.date = date;
    	}

	public Date getFudate() {
		return fudate;
	}

	public void setFudate(Date fudate) {
		this.fudate = fudate;
	}

}
