package com.ikkong.cars.service.impl;

import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.cars.model.Carsgas;
import com.ikkong.cars.service.CarsgasService;

/**
 * Generated by Blade.
 * 2018-08-20 15:42:02
 */
public class CarsgasServiceImpl extends BaseService<Carsgas> implements CarsgasService{

}
