package com.ikkong.cars.service.impl;

import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.cars.model.Cars;
import com.ikkong.cars.service.CarsService;

/**
 * Generated by Blade.
 * 2018-08-17 09:07:58
 */
public class CarsServiceImpl extends BaseService<Cars> implements CarsService{

}
