package com.ikkong.cars.service.impl;

import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.cars.model.Carslog;
import com.ikkong.cars.service.CarslogService;

/**
 * Generated by Blade.
 * 2018-08-17 09:07:58
 */
public class CarslogServiceImpl extends BaseService<Carslog> implements CarslogService{

}
