package com.ikkong.files.service;

import com.ikkong.core.base.service.IService;
import com.ikkong.files.model.Fileslog;

/**
 * Generated by Blade.
 * 2018-07-16 10:24:02
 */
public interface FileslogService extends IService<Fileslog>{

}
