package com.ikkong.files.service;

import com.ikkong.core.base.service.IService;
import com.ikkong.files.model.Filesvislog;

/**
 * Generated by Blade.
 * 2018-07-27 16:36:20
 */
public interface FilesvislogService extends IService<Filesvislog>{

}
