package com.ikkong.unforgot.model;

import org.beetl.sql.core.annotatoin.AutoID;
import org.beetl.sql.core.annotatoin.Table;
import com.ikkong.core.annotation.BindID;
import com.ikkong.core.model.BaseModel;

import java.util.Date;

/**
 * Generated by Blade.
 * 2018-08-16 22:13:57
 */
@Table(name = "nsl_unforgot")
@BindID(name = "id")
@SuppressWarnings("serial")
public class Unforgot extends BaseModel {
    	private Integer id;
    	private Integer status; //级别
    	private Integer u_id; //用户
    	private String content; //内容
    	private Date date; //日期

    	@AutoID
    	public Integer getId() {
    		return id;
    	}

    	public void setId(Integer id) {
    		this.id = id;
    	}

    	public Integer getStatus() {
    		return status;
    	}

    	public void setStatus(Integer status) {
    		this.status = status;
    	}

    	public Integer getU_id() {
    		return u_id;
    	}

    	public void setU_id(Integer u_id) {
    		this.u_id = u_id;
    	}

    	public String getContent() {
    		return content;
    	}

    	public void setContent(String content) {
    		this.content = content;
    	}

    	public Date getDate() {
    		return date;
    	}

    	public void setDate(Date date) {
    		this.date = date;
    	}

}
