package com.ikkong.files.service.impl;

import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.files.model.Files;
import com.ikkong.files.service.FilesService;

/**
 * Generated by Blade.
 * 2018-07-16 10:24:02
 */
public class FilesServiceImpl extends BaseService<Files> implements FilesService{

}
