package com.ikkong.files.service.impl;

import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.files.model.Fileslog;
import com.ikkong.files.service.FileslogService;

/**
 * Generated by Blade.
 * 2018-07-16 10:24:02
 */
public class FileslogServiceImpl extends BaseService<Fileslog> implements FileslogService{

}
