package com.ikkong.files.service.impl;

import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.files.model.Filesvislog;
import com.ikkong.files.service.FilesvislogService;

/**
 * Generated by Blade.
 * 2018-07-27 16:36:20
 */
public class FilesvislogServiceImpl extends BaseService<Filesvislog> implements FilesvislogService{

}
