package com.ikkong.cars.service;

import com.ikkong.core.base.service.IService;
import com.ikkong.cars.model.Carslog;

/**
 * Generated by Blade.
 * 2018-08-17 09:07:58
 */
public interface CarslogService extends IService<Carslog>{

}
