package com.ikkong.cars.service;

import com.ikkong.core.base.service.IService;
import com.ikkong.cars.model.Cars;

/**
 * Generated by Blade.
 * 2018-08-17 09:07:58
 */
public interface CarsService extends IService<Cars>{

}
