package com.ikkong.cars.service;

import com.ikkong.core.base.service.IService;
import com.ikkong.cars.model.Carsgas;

/**
 * Generated by Blade.
 * 2018-08-20 15:42:02
 */
public interface CarsgasService extends IService<Carsgas>{

}
