package com.ikkong.unforgot.service;

import com.ikkong.core.base.service.IService;
import com.ikkong.unforgot.model.Unforgot;

/**
 * Generated by Blade.
 * 2018-08-16 22:13:57
 */
public interface UnforgotService extends IService<Unforgot>{

}
