package com.ikkong.casher.controller;

import java.util.Map;

import com.ikkong.casher.model.Casher;
import com.ikkong.core.base.BaseController;
import com.ikkong.core.dao.Blade;
import com.ikkong.core.jfinal.ext.kit.JsonKit;
import com.ikkong.core.jfinal.ext.shiro.ShiroKit;
import com.ikkong.system.controller.base.UrlPermissController;
import com.ikkong.casher.model.Casherlog;
import com.ikkong.casher.service.CasherlogService;
import com.ikkong.casher.service.impl.CasherlogServiceImpl;

/**
 * Generated by Blade.
 * 2018-07-23 16:28:52
 */
public class CasherlogController extends UrlPermissController {
	private static String CODE = "casherlog";
	private static String PERFIX = "nsl_casher_log";
	private static String LIST_SOURCE = "Casherlog.list";
	private static String BASE_PATH = "/platform/casherlog/";
	
	CasherlogService service = new CasherlogServiceImpl();
	
	public void index() {
		setAttr("code", CODE);
		render(BASE_PATH + "casherlog.html");
	}

	public void add() {
		setAttr("code", CODE);
		render(BASE_PATH + "casherlog_add.html");
	}

	public void edit() {
		String id = getPara(0);
		Casherlog casherlog = service.findById(id);
		setAttr("model", JsonKit.toJson(casherlog));
		setAttr("id", id);
		setAttr("code", CODE);
		render(BASE_PATH + "casherlog_edit.html");
	}

	public void view() {
		String id = getPara(0);
		Casherlog casherlog = service.findById(id);
		setAttr("model", JsonKit.toJson(casherlog));
		setAttr("id", id);
		setAttr("code", CODE);
		render(BASE_PATH + "casherlog_view.html");
	}

	public void list() {
		Object grid = paginate(LIST_SOURCE);
		renderJson(grid);
	}

	public void save() {
        String mode = getPara("mode", "");
        Casherlog casherlog = mapping(PERFIX, Casherlog.class);
        if(casherlog==null){
            renderJson(error(SAVE_FAIL_MSG));
            return;
        }





        if("back".equals(mode)){
            Casher casher = Blade.create(Casher.class).findById(casherlog.getC_id());
            if( casherlog.getIspass()!= null && casherlog.getIspass() == 3){
                if(ShiroKit.getUser().getRoleList().contains("13")){//部门领导
                    casher.setStatus(2);
                }else if(ShiroKit.getUser().getRoleList().contains("11")){//财务初审
                    casher.setStatus(3);
                }else if(ShiroKit.getUser().getRoleList().contains("9")){//领导班子
                    casher.setStatus(4);
                }else if(ShiroKit.getUser().getRoleList().contains("8")){//总经理
                    casher.setStatus(5);
                }else if(ShiroKit.getUser().getRoleList().contains("12")){//财务终审
                    casher.setStatus(6);
                }

            }else if(casherlog.getIspass()!= null && casherlog.getIspass() == 2){
                if(ShiroKit.getUser().getRoleList().contains("13")){//部门领导
                    casher.setStatus(8);
                }else if(ShiroKit.getUser().getRoleList().contains("11")){//财务初审
                    casher.setStatus(9);
                }else if(ShiroKit.getUser().getRoleList().contains("9")){//领导班子
                    casher.setStatus(10);
                }else if(ShiroKit.getUser().getRoleList().contains("8")){//总经理
                    casher.setStatus(11);
                }else if(ShiroKit.getUser().getRoleList().contains("12")){//财务终审
                    casher.setStatus(12);
                }
            }
            Blade.create(Casher.class).update(casher);


        }
		boolean temp = service.save(casherlog);
		if (temp) {
			renderJson(success(SAVE_SUCCESS_MSG));
		} else {
			renderJson(error(SAVE_FAIL_MSG));
		}
	}

	public void update() {
		Casherlog casherlog = mapping(PERFIX, Casherlog.class);
		boolean temp = service.update(casherlog);
		if (temp) {
			renderJson(success(UPDATE_SUCCESS_MSG));
		} else {
			renderJson(error(UPDATE_FAIL_MSG));
		}
	}

	public void remove() {
		String ids = getPara("ids");
		int cnt = service.deleteByIds(ids);
		if (cnt > 0) {
			renderJson(success(DEL_SUCCESS_MSG));
		} else {
			renderJson(error(DEL_FAIL_MSG));
		}
	}
}
