package com.ikkong.casher.controller;

import java.util.Map;
import com.ikkong.core.base.BaseController;
import com.ikkong.core.jfinal.ext.kit.JsonKit;
import com.ikkong.system.controller.base.UrlPermissController;
import com.ikkong.casher.model.Casherdetail;
import com.ikkong.casher.service.CasherdetailService;
import com.ikkong.casher.service.impl.CasherdetailServiceImpl;

/**
 * Generated by Blade.
 * 2018-07-23 14:58:05
 */
public class CasherdetailController extends UrlPermissController {
	private static String CODE = "casherdetail";
	private static String PERFIX = "nsl_casher_detail";
	private static String LIST_SOURCE = "Casherdetail.list";
	private static String BASE_PATH = "/platform/casherdetail/";
	
	CasherdetailService service = new CasherdetailServiceImpl();
	
	public void index() {
		setAttr("code", CODE);
		render(BASE_PATH + "casherdetail.html");
	}

	public void add() {
		setAttr("code", CODE);
		render(BASE_PATH + "casherdetail_add.html");
	}

	public void edit() {
		String id = getPara(0);
		Casherdetail casherdetail = service.findById(id);
		setAttr("model", JsonKit.toJson(casherdetail));
		setAttr("id", id);
		setAttr("code", CODE);
		render(BASE_PATH + "casherdetail_edit.html");
	}

	public void view() {
		String id = getPara(0);
		Casherdetail casherdetail = service.findById(id);
		setAttr("model", JsonKit.toJson(casherdetail));
		setAttr("id", id);
		setAttr("code", CODE);
		render(BASE_PATH + "casherdetail_view.html");
	}

	public void list() {
		Object grid = paginate(LIST_SOURCE);
		renderJson(grid);
	}

	public void save() {
		Casherdetail casherdetail = mapping(PERFIX, Casherdetail.class);
		boolean temp = service.save(casherdetail);
		if (temp) {
			renderJson(success(SAVE_SUCCESS_MSG));
		} else {
			renderJson(error(SAVE_FAIL_MSG));
		}
	}

	public void update() {
		Casherdetail casherdetail = mapping(PERFIX, Casherdetail.class);
		boolean temp = service.update(casherdetail);
		if (temp) {
			renderJson(success(UPDATE_SUCCESS_MSG));
		} else {
			renderJson(error(UPDATE_FAIL_MSG));
		}
	}

	public void remove() {
		String ids = getPara("ids");
		int cnt = service.deleteByIds(ids);
		if (cnt > 0) {
			renderJson(success(DEL_SUCCESS_MSG));
		} else {
			renderJson(error(DEL_FAIL_MSG));
		}
	}
}
