package com.ikkong.casher.service;

import com.ikkong.core.base.service.IService;
import com.ikkong.casher.model.Casherlog;

/**
 * Generated by Blade.
 * 2018-07-23 16:28:52
 */
public interface CasherlogService extends IService<Casherlog>{

}
