package com.ikkong.casher.service;

import com.ikkong.core.base.service.IService;
import com.ikkong.casher.model.Casherdetail;

/**
 * Generated by Blade.
 * 2018-07-23 14:58:05
 */
public interface CasherdetailService extends IService<Casherdetail>{

}
