package com.ikkong.casher.service;

import com.ikkong.core.base.service.IService;
import com.ikkong.casher.model.Casher;

/**
 * Generated by Blade.
 * 2018-07-23 14:59:02
 */
public interface CasherService extends IService<Casher>{

}
