package com.ikkong.cars.model;

import org.beetl.sql.core.annotatoin.AutoID;
import org.beetl.sql.core.annotatoin.Table;
import com.ikkong.core.annotation.BindID;
import com.ikkong.core.model.BaseModel;

/**
 * Generated by Blade.
 * 2018-08-17 09:07:58
 */
@Table(name = "nsl_cars")
@BindID(name = "id")
@SuppressWarnings("serial")
public class Cars extends BaseModel {
    	private Integer id;
    	private Integer status; //状态
    	private Integer version;
    	private String name; //驾驶员
    	private String num; //车牌号
    	private String pic; //照片
    	private String remarks; //备注

    	@AutoID
    	public Integer getId() {
    		return id;
    	}

    	public void setId(Integer id) {
    		this.id = id;
    	}

    	public Integer getStatus() {
    		return status;
    	}

    	public void setStatus(Integer status) {
    		this.status = status;
    	}

    	public Integer getVersion() {
    		return version;
    	}

    	public void setVersion(Integer version) {
    		this.version = version;
    	}

    	public String getName() {
    		return name;
    	}

    	public void setName(String name) {
    		this.name = name;
    	}

    	public String getNum() {
    		return num;
    	}

    	public void setNum(String num) {
    		this.num = num;
    	}

    	public String getPic() {
    		return pic;
    	}

    	public void setPic(String pic) {
    		this.pic = pic;
    	}

    	public String getRemarks() {
    		return remarks;
    	}

    	public void setRemarks(String remarks) {
    		this.remarks = remarks;
    	}

}
