package com.ikkong.cars.model;

import org.beetl.sql.core.annotatoin.AutoID;
import org.beetl.sql.core.annotatoin.Table;
import com.ikkong.core.annotation.BindID;
import com.ikkong.core.model.BaseModel;

import java.math.BigDecimal;
import java.util.Date;

/**
 * Generated by Blade.
 * 2018-08-20 15:42:02
 */
@Table(name = "nsl_cars_gas")
@BindID(name = "id")
@SuppressWarnings("serial")
public class Carsgas extends BaseModel {
    	private Integer id;
    	private Integer c_id; //车辆
    	private Integer mileage; //当前里程数
    	private Integer u_id; //经办人
    	private Integer version;
    	private BigDecimal gas; //加油量
    	private BigDecimal money; //金额
    	private Date date; //日期

    	@AutoID

    	public Integer getId() {
    		return id;
    	}

    	public void setId(Integer id) {
    		this.id = id;
    	}

    	public Integer getC_id() {
    		return c_id;
    	}

    	public void setC_id(Integer c_id) {
    		this.c_id = c_id;
    	}

    	public Integer getMileage() {
    		return mileage;
    	}

    	public void setMileage(Integer mileage) {
    		this.mileage = mileage;
    	}

    	public Integer getU_id() {
    		return u_id;
    	}

    	public void setU_id(Integer u_id) {
    		this.u_id = u_id;
    	}

    	public Integer getVersion() {
    		return version;
    	}

    	public void setVersion(Integer version) {
    		this.version = version;
    	}

    	public BigDecimal getGas() {
    		return gas;
    	}

    	public void setGas(BigDecimal gas) {
    		this.gas = gas;
    	}

    	public BigDecimal getMoney() {
    		return money;
    	}

    	public void setMoney(BigDecimal money) {
    		this.money = money;
    	}

    	public Date getDate() {
    		return date;
    	}

    	public void setDate(Date date) {
    		this.date = date;
    	}

}
