package com.ikkong.cars.model;

import org.beetl.sql.core.annotatoin.AutoID;
import org.beetl.sql.core.annotatoin.Table;
import com.ikkong.core.annotation.BindID;
import com.ikkong.core.model.BaseModel;

import java.util.Date;

/**
 * Generated by Blade.
 * 2018-08-17 09:07:58
 */
@Table(name = "nsl_carslog")
@BindID(name = "id")
@SuppressWarnings("serial")
public class Carslog extends BaseModel {
    	private Integer id;
    	private Integer c_id; //派车
    	private Integer p_id; //派车人
    	private Integer version;
    	private String cause; //派车原因
    	private String uname; //乘客名字
    	private Date over; //结束时间
    	private Date start; //起始时间
	private String cnum; //起始时间

    	@AutoID
    	public Integer getId() {
    		return id;
    	}

    	public void setId(Integer id) {
    		this.id = id;
    	}

    	public Integer getC_id() {
    		return c_id;
    	}

    	public void setC_id(Integer c_id) {
    		this.c_id = c_id;
    	}

    	public Integer getP_id() {
    		return p_id;
    	}

    	public void setP_id(Integer p_id) {
    		this.p_id = p_id;
    	}

    	public Integer getVersion() {
    		return version;
    	}

    	public void setVersion(Integer version) {
    		this.version = version;
    	}

    	public String getCause() {
    		return cause;
    	}

    	public void setCause(String cause) {
    		this.cause = cause;
    	}

	public String getCnum() {
		return cnum;
	}

	public void setCnum(String cnum) {
		this.cnum = cnum;
	}


	public String getUname() {
    		return uname;
    	}

    	public void setUname(String uname) {
    		this.uname = uname;
    	}

    	public Date getOver() {
    		return over;
    	}

    	public void setOver(Date over) {
    		this.over = over;
    	}

    	public Date getStart() {
    		return start;
    	}

    	public void setStart(Date start) {
    		this.start = start;
    	}

}
