package com.ikkong.unforgot.service.impl;

import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.unforgot.model.Unforgot;
import com.ikkong.unforgot.service.UnforgotService;

/**
 * Generated by Blade.
 * 2018-08-16 22:13:57
 */
public class UnforgotServiceImpl extends BaseService<Unforgot> implements UnforgotService{

}
