package com.ikkong.goods.service.impl;

import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.goods.model.Goodssplog;
import com.ikkong.goods.service.GoodssplogService;

/**
 * Generated by Blade.
 * 2018-07-25 09:28:36
 */
public class GoodssplogServiceImpl extends BaseService<Goodssplog> implements GoodssplogService{

}
