package com.ikkong.goods.service.impl;

import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.goods.model.Goodslog;
import com.ikkong.goods.service.GoodslogService;

/**
 * Generated by Blade.
 * 2018-07-25 09:28:36
 */
public class GoodslogServiceImpl extends BaseService<Goodslog> implements GoodslogService{

}
