package com.ikkong.goods.service.impl;

import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.goods.model.Goods;
import com.ikkong.goods.service.GoodsService;

/**
 * Generated by Blade.
 * 2018-07-25 09:28:36
 */
public class GoodsServiceImpl extends BaseService<Goods> implements GoodsService{

}
