package com.ikkong.goods.model;

import org.beetl.sql.core.annotatoin.AutoID;
import org.beetl.sql.core.annotatoin.Table;
import com.ikkong.core.annotation.BindID;
import com.ikkong.core.model.BaseModel;

/**
 * Generated by Blade.
 * 2018-07-25 09:28:36
 */
@Table(name = "nsl_goods_splog")
@BindID(name = "id")
@SuppressWarnings("serial")
public class Goodssplog extends BaseModel {
    	private Integer id;
    	private Integer gl_id; //申请号
    	private Integer sp_id; //审批人
    	private Integer version;
    	private String sp_opinion; //审批意见

    	@AutoID
    	public Integer getId() {
    		return id;
    	}

    	public void setId(Integer id) {
    		this.id = id;
    	}

    	public Integer getGl_id() {
    		return gl_id;
    	}

    	public void setGl_id(Integer gl_id) {
    		this.gl_id = gl_id;
    	}

    	public Integer getSp_id() {
    		return sp_id;
    	}

    	public void setSp_id(Integer sp_id) {
    		this.sp_id = sp_id;
    	}

    	public Integer getVersion() {
    		return version;
    	}

    	public void setVersion(Integer version) {
    		this.version = version;
    	}

    	public String getSp_opinion() {
    		return sp_opinion;
    	}

    	public void setSp_opinion(String sp_opinion) {
    		this.sp_opinion = sp_opinion;
    	}

}
