package com.ikkong.goods.model;

import org.beetl.sql.core.annotatoin.AutoID;
import org.beetl.sql.core.annotatoin.Table;
import com.ikkong.core.annotation.BindID;
import com.ikkong.core.model.BaseModel;

/**
 * Generated by Blade.
 * 2018-07-25 09:28:36
 */
@Table(name = "nsl_goods_log")
@BindID(name = "id")
@SuppressWarnings("serial")
public class Goodslog extends BaseModel {
    	private Integer id;
    	private Integer date; //申请时间
    	private Integer g_id; //办公用品
    	private Integer num; //申请数量
    	private Integer sp_id; //审批人
    	private Integer sp_ispass; //是否通过
    	private Integer u_id; //领取人
    	private Integer version;
    	private Integer visible1; //可见人
    	private String sp_opinion; //审批意见

    	@AutoID
    	public Integer getId() {
    		return id;
    	}

    	public void setId(Integer id) {
    		this.id = id;
    	}

    	public Integer getDate() {
    		return date;
    	}

    	public void setDate(Integer date) {
    		this.date = date;
    	}

    	public Integer getG_id() {
    		return g_id;
    	}

    	public void setG_id(Integer g_id) {
    		this.g_id = g_id;
    	}

    	public Integer getNum() {
    		return num;
    	}

    	public void setNum(Integer num) {
    		this.num = num;
    	}

    	public Integer getSp_id() {
    		return sp_id;
    	}

    	public void setSp_id(Integer sp_id) {
    		this.sp_id = sp_id;
    	}

    	public Integer getSp_ispass() {
    		return sp_ispass;
    	}

    	public void setSp_ispass(Integer sp_ispass) {
    		this.sp_ispass = sp_ispass;
    	}

    	public Integer getU_id() {
    		return u_id;
    	}

    	public void setU_id(Integer u_id) {
    		this.u_id = u_id;
    	}

    	public Integer getVersion() {
    		return version;
    	}

    	public void setVersion(Integer version) {
    		this.version = version;
    	}

    	public Integer getVisible1() {
    		return visible1;
    	}

    	public void setVisible1(Integer visible1) {
    		this.visible1 = visible1;
    	}

    	public String getSp_opinion() {
    		return sp_opinion;
    	}

    	public void setSp_opinion(String sp_opinion) {
    		this.sp_opinion = sp_opinion;
    	}

}
