package com.ikkong.goods.model;

import org.beetl.sql.core.annotatoin.AutoID;
import org.beetl.sql.core.annotatoin.Table;
import com.ikkong.core.annotation.BindID;
import com.ikkong.core.model.BaseModel;

/**
 * Generated by Blade.
 * 2018-07-25 09:28:36
 */
@Table(name = "nsl_goods")
@BindID(name = "id")
@SuppressWarnings("serial")
public class Goods extends BaseModel {
    	private Integer id;
    	private Integer num; //库存
    	private Integer price; //单价
    	private Integer type; //类型
    	private Integer version;
    	private String code; //条码
    	private String guige; //规格
    	private String name; //名称

    	@AutoID
    	public Integer getId() {
    		return id;
    	}

    	public void setId(Integer id) {
    		this.id = id;
    	}

    	public Integer getNum() {
    		return num;
    	}

    	public void setNum(Integer num) {
    		this.num = num;
    	}

    	public Integer getPrice() {
    		return price;
    	}

    	public void setPrice(Integer price) {
    		this.price = price;
    	}

    	public Integer getType() {
    		return type;
    	}

    	public void setType(Integer type) {
    		this.type = type;
    	}

    	public Integer getVersion() {
    		return version;
    	}

    	public void setVersion(Integer version) {
    		this.version = version;
    	}

    	public String getCode() {
    		return code;
    	}

    	public void setCode(String code) {
    		this.code = code;
    	}

    	public String getGuige() {
    		return guige;
    	}

    	public void setGuige(String guige) {
    		this.guige = guige;
    	}

    	public String getName() {
    		return name;
    	}

    	public void setName(String name) {
    		this.name = name;
    	}

}
