package com.ikkong.goods.controller;

import java.util.Map;
import com.ikkong.core.base.BaseController;
import com.ikkong.core.jfinal.ext.kit.JsonKit;
import com.ikkong.system.controller.base.UrlPermissController;
import com.ikkong.goods.model.Goodslog;
import com.ikkong.goods.service.GoodslogService;
import com.ikkong.goods.service.impl.GoodslogServiceImpl;

/**
 * Generated by Blade.
 * 2018-07-25 09:28:36
 */
public class GoodslogController extends UrlPermissController {
	private static String CODE = "goodslog";
	private static String PERFIX = "nsl_goods_log";
	private static String LIST_SOURCE = "Goodslog.list";
	private static String BASE_PATH = "/platform/goodslog/";
	
	GoodslogService service = new GoodslogServiceImpl();
	
	public void index() {
		setAttr("code", CODE);
		render(BASE_PATH + "goodslog.html");
	}

	public void add() {
		setAttr("code", CODE);
		render(BASE_PATH + "goodslog_add.html");
	}

	public void edit() {
		String id = getPara(0);
		Goodslog goodslog = service.findById(id);
		setAttr("model", JsonKit.toJson(goodslog));
		setAttr("id", id);
		setAttr("code", CODE);
		render(BASE_PATH + "goodslog_edit.html");
	}

	public void view() {
		String id = getPara(0);
		Goodslog goodslog = service.findById(id);
		setAttr("model", JsonKit.toJson(goodslog));
		setAttr("id", id);
		setAttr("code", CODE);
		render(BASE_PATH + "goodslog_view.html");
	}

	public void list() {
		Object grid = paginate(LIST_SOURCE);
		renderJson(grid);
	}

	public void save() {
		Goodslog goodslog = mapping(PERFIX, Goodslog.class);
		boolean temp = service.save(goodslog);
		if (temp) {
			renderJson(success(SAVE_SUCCESS_MSG));
		} else {
			renderJson(error(SAVE_FAIL_MSG));
		}
	}

	public void update() {
		Goodslog goodslog = mapping(PERFIX, Goodslog.class);
		boolean temp = service.update(goodslog);
		if (temp) {
			renderJson(success(UPDATE_SUCCESS_MSG));
		} else {
			renderJson(error(UPDATE_FAIL_MSG));
		}
	}

	public void remove() {
		String ids = getPara("ids");
		int cnt = service.deleteByIds(ids);
		if (cnt > 0) {
			renderJson(success(DEL_SUCCESS_MSG));
		} else {
			renderJson(error(DEL_FAIL_MSG));
		}
	}
}
