package com.ikkong.casher.model;

import org.beetl.sql.core.annotatoin.AutoID;
import org.beetl.sql.core.annotatoin.Table;
import com.ikkong.core.annotation.BindID;
import com.ikkong.core.model.BaseModel;

import java.util.Date;

/**
 * Generated by Blade.
 * 2018-07-23 16:28:52
 */
@Table(name = "nsl_casher_log")
@BindID(name = "id")
@SuppressWarnings("serial")
public class Casherlog extends BaseModel {
    	private Integer id;
    	private Integer c_id; //报销单
    	private Integer ispass; //是否通过
    	private Integer u_id; //审批人
    	private Integer version;
    	private String opinion; //审批意见
    	private Date date; //审批时间

    	@AutoID
    	public Integer getId() {
    		return id;
    	}

    	public void setId(Integer id) {
    		this.id = id;
    	}

    	public Integer getC_id() {
    		return c_id;
    	}

    	public void setC_id(Integer c_id) {
    		this.c_id = c_id;
    	}

    	public Integer getIspass() {
    		return ispass;
    	}

    	public void setIspass(Integer ispass) {
    		this.ispass = ispass;
    	}

    	public Integer getU_id() {
    		return u_id;
    	}

    	public void setU_id(Integer u_id) {
    		this.u_id = u_id;
    	}

    	public Integer getVersion() {
    		return version;
    	}

    	public void setVersion(Integer version) {
    		this.version = version;
    	}

    	public String getOpinion() {
    		return opinion;
    	}

    	public void setOpinion(String opinion) {
    		this.opinion = opinion;
    	}

    	public Date getDate() {
    		return date;
    	}

    	public void setDate(Date date) {
    		this.date = date;
    	}

}
