package com.ikkong.casher.model;

import org.beetl.sql.core.annotatoin.AutoID;
import org.beetl.sql.core.annotatoin.Table;
import com.ikkong.core.annotation.BindID;
import com.ikkong.core.model.BaseModel;

import java.util.Date;

/**
 * Generated by Blade.
 * 2018-07-23 14:59:02
 */
@Table(name = "nsl_casher")
@BindID(name = "id")
@SuppressWarnings("serial")
public class Casher extends BaseModel {
    	private Integer id;
    	private Integer d_id; //部门
    	private Integer num; //票据张数
    	private Integer status; //审核状态
    	private Integer u_id; //经办人
    	private Integer version;
    	private String cause; //事由
    	private String opinion; //审批意见
    	private String title; //标题
    	private String type; //报销类别
    	private String visible; //可见人
	private String selectname; //可见人
	private String imgs; //可见人
    	private Date date; //时间
    	private Date over; //结束时间
    	private Date start; //开始时间

    	@AutoID
    	public Integer getId() {
    		return id;
    	}

    	public void setId(Integer id) {
    		this.id = id;
    	}

    	public Integer getD_id() {
    		return d_id;
    	}

    	public void setD_id(Integer d_id) {
    		this.d_id = d_id;
    	}

    	public Integer getNum() {
    		return num;
    	}

    	public void setNum(Integer num) {
    		this.num = num;
    	}

    	public Integer getStatus() {
    		return status;
    	}

    	public void setStatus(Integer status) {
    		this.status = status;
    	}

    	public Integer getU_id() {
    		return u_id;
    	}

    	public void setU_id(Integer u_id) {
    		this.u_id = u_id;
    	}

    	public Integer getVersion() {
    		return version;
    	}

    	public void setVersion(Integer version) {
    		this.version = version;
    	}

	public String getSelectname() {
		return selectname;
	}

	public void setSelectname(String selectname) {
		this.selectname = selectname;
	}
		public String getImgs() {
			return imgs;
		}

		public void setImgs(String imgs) {
		this.imgs = imgs;
	}

    	public String getCause() {
    		return cause;
    	}

    	public void setCause(String cause) {
    		this.cause = cause;
    	}

    	public String getOpinion() {
    		return opinion;
    	}

    	public void setOpinion(String opinion) {
    		this.opinion = opinion;
    	}

    	public String getTitle() {
    		return title;
    	}

    	public void setTitle(String title) {
    		this.title = title;
    	}

    	public String getType() {
    		return type;
    	}

    	public void setType(String type) {
    		this.type = type;
    	}

    	public String getVisible() {
    		return visible;
    	}

    	public void setVisible(String visible) {
    		this.visible = visible;
    	}

    	public Date getDate() {
    		return date;
    	}

    	public void setDate(Date date) {
    		this.date = date;
    	}

    	public Date getOver() {
    		return over;
    	}

    	public void setOver(Date over) {
    		this.over = over;
    	}

    	public Date getStart() {
    		return start;
    	}

    	public void setStart(Date start) {
    		this.start = start;
    	}

}
