package com.ikkong.casher.model;

import org.beetl.sql.core.annotatoin.AutoID;
import org.beetl.sql.core.annotatoin.Table;
import com.ikkong.core.annotation.BindID;
import com.ikkong.core.model.BaseModel;

/**
 * Generated by Blade.
 * 2018-07-23 14:58:06
 */
@Table(name = "nsl_casher_detail")
@BindID(name = "id")
@SuppressWarnings("serial")
public class Casherdetail extends BaseModel {
    	private Integer id;
    	private Integer c_id; //报销单号
    	private Integer version;
    	private String detail; //说明
    	private String img; //图片

    	@AutoID
    	public Integer getId() {
    		return id;
    	}

    	public void setId(Integer id) {
    		this.id = id;
    	}

    	public Integer getC_id() {
    		return c_id;
    	}

    	public void setC_id(Integer c_id) {
    		this.c_id = c_id;
    	}

    	public Integer getVersion() {
    		return version;
    	}

    	public void setVersion(Integer version) {
    		this.version = version;
    	}

    	public String getDetail() {
    		return detail;
    	}

    	public void setDetail(String detail) {
    		this.detail = detail;
    	}

    	public String getImg() {
    		return img;
    	}

    	public void setImg(String img) {
    		this.img = img;
    	}

}
